version: 2
image: ubuntu:16.04
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Installing dependencies
          command: yarn

      - run:
          name: Linting source files
          command: yarn lint

      - run:
          name: Building production bundle
          command: yarn build

      - run:
          name: Running tests
          command: yarn test

      - run:
          name: Building styleguidist
          command: yarn styleguide:build

      - run:
          name: Building and uploading storybook for visual diff
          command: |
            scripts/fetch-skin.sh
            yarn percy; true

